#[cfg(test)]
mod tests;

pub mod address_mode;
pub mod mnemonics;
pub mod op_codes;

/// Instruction represents a single 6502 instruction containing a mnemonic,
/// address mode and optionally any operands.
#[derive(Clone, Copy, PartialEq, Debug)]
pub struct Instruction {
    mnemonic: mnemonics::Mnemonic,
    address_mode: address_mode::AddressModeWithOperand,
}

impl Into<op_codes::OpCode> for Instruction {
    fn into(self) -> op_codes::OpCode {
        use address_mode::AddressModeWithOperand;
        use mnemonics::Mnemonic;
        match (self.mnemonic, self.address_mode) {
            (Mnemonic::BRK, AddressModeWithOperand::Implied) => 0x00,
            (Mnemonic::ORA, AddressModeWithOperand::IndexedIndirect(_)) => 0x01,
            (Mnemonic::ORA, AddressModeWithOperand::ZeroPage(_)) => 0x05,
            (Mnemonic::ASL, AddressModeWithOperand::ZeroPage(_)) => 0x06,
            (Mnemonic::PHP, AddressModeWithOperand::Implied) => 0x08,
            (Mnemonic::ORA, AddressModeWithOperand::Immediate(_)) => 0x09,
            (Mnemonic::ASL, AddressModeWithOperand::Accumulator) => 0x0a,
            (Mnemonic::ORA, AddressModeWithOperand::Absolute(_)) => 0x0d,
            (Mnemonic::ASL, AddressModeWithOperand::Absolute(_)) => 0x0e,
            (Mnemonic::BPL, AddressModeWithOperand::Relative(_)) => 0x10,
            (Mnemonic::ORA, AddressModeWithOperand::IndirectIndexed(_)) => 0x11,
            (Mnemonic::ORA, AddressModeWithOperand::ZeroPageIndexedWithX(_)) => 0x15,
            (Mnemonic::ASL, AddressModeWithOperand::ZeroPageIndexedWithX(_)) => 0x16,
            (Mnemonic::CLC, AddressModeWithOperand::Implied) => 0x18,
            (Mnemonic::ORA, AddressModeWithOperand::AbsoluteIndexedWithY(_)) => 0x19,
            (Mnemonic::ORA, AddressModeWithOperand::AbsoluteIndexedWithX(_)) => 0x1d,
            (Mnemonic::ASL, AddressModeWithOperand::AbsoluteIndexedWithX(_)) => 0x1e,
            (Mnemonic::JSR, AddressModeWithOperand::Absolute(_)) => 0x20,
            (Mnemonic::AND, AddressModeWithOperand::IndexedIndirect(_)) => 0x21,
            (Mnemonic::BIT, AddressModeWithOperand::ZeroPage(_)) => 0x24,
            (Mnemonic::AND, AddressModeWithOperand::ZeroPage(_)) => 0x25,
            (Mnemonic::ROL, AddressModeWithOperand::ZeroPage(_)) => 0x26,
            (Mnemonic::PLP, AddressModeWithOperand::Implied) => 0x28,
            (Mnemonic::AND, AddressModeWithOperand::Immediate(_)) => 0x29,
            (Mnemonic::ROL, AddressModeWithOperand::Accumulator) => 0x2a,
            (Mnemonic::BIT, AddressModeWithOperand::Absolute(_)) => 0x2c,
            (Mnemonic::AND, AddressModeWithOperand::Absolute(_)) => 0x2d,
            (Mnemonic::ROL, AddressModeWithOperand::Absolute(_)) => 0x2e,
            (Mnemonic::BMI, AddressModeWithOperand::Relative(_)) => 0x30,
            (Mnemonic::AND, AddressModeWithOperand::IndirectIndexed(_)) => 0x31,
            (Mnemonic::AND, AddressModeWithOperand::ZeroPageIndexedWithX(_)) => 0x35,
            (Mnemonic::ROL, AddressModeWithOperand::ZeroPageIndexedWithX(_)) => 0x36,
            (Mnemonic::SEC, AddressModeWithOperand::Implied) => 0x38,
            (Mnemonic::AND, AddressModeWithOperand::AbsoluteIndexedWithY(_)) => 0x39,
            (Mnemonic::AND, AddressModeWithOperand::AbsoluteIndexedWithX(_)) => 0x3d,
            (Mnemonic::ROL, AddressModeWithOperand::AbsoluteIndexedWithX(_)) => 0x3e,
            (Mnemonic::RTI, AddressModeWithOperand::Implied) => 0x40,
            (Mnemonic::EOR, AddressModeWithOperand::IndexedIndirect(_)) => 0x41,
            (Mnemonic::EOR, AddressModeWithOperand::ZeroPage(_)) => 0x45,
            (Mnemonic::LSR, AddressModeWithOperand::ZeroPage(_)) => 0x46,
            (Mnemonic::PHA, AddressModeWithOperand::Implied) => 0x48,
            (Mnemonic::EOR, AddressModeWithOperand::Immediate(_)) => 0x49,
            (Mnemonic::LSR, AddressModeWithOperand::Accumulator) => 0x4a,
            (Mnemonic::JMP, AddressModeWithOperand::Absolute(_)) => 0x4c,
            (Mnemonic::EOR, AddressModeWithOperand::Absolute(_)) => 0x4d,
            (Mnemonic::LSR, AddressModeWithOperand::Absolute(_)) => 0x4e,
            (Mnemonic::BVC, AddressModeWithOperand::Relative(_)) => 0x50,
            (Mnemonic::EOR, AddressModeWithOperand::IndirectIndexed(_)) => 0x51,
            (Mnemonic::EOR, AddressModeWithOperand::ZeroPageIndexedWithX(_)) => 0x55,
            (Mnemonic::LSR, AddressModeWithOperand::ZeroPageIndexedWithX(_)) => 0x56,
            (Mnemonic::CLI, AddressModeWithOperand::Implied) => 0x58,
            (Mnemonic::EOR, AddressModeWithOperand::AbsoluteIndexedWithY(_)) => 0x59,
            (Mnemonic::EOR, AddressModeWithOperand::AbsoluteIndexedWithX(_)) => 0x5d,
            (Mnemonic::LSR, AddressModeWithOperand::AbsoluteIndexedWithX(_)) => 0x5e,
            (Mnemonic::RTS, AddressModeWithOperand::Implied) => 0x60,
            (Mnemonic::ADC, AddressModeWithOperand::IndexedIndirect(_)) => 0x61,
            (Mnemonic::ADC, AddressModeWithOperand::ZeroPage(_)) => 0x65,
            (Mnemonic::ROR, AddressModeWithOperand::ZeroPage(_)) => 0x66,
            (Mnemonic::PLA, AddressModeWithOperand::Implied) => 0x68,
            (Mnemonic::ADC, AddressModeWithOperand::Immediate(_)) => 0x69,
            (Mnemonic::ROR, AddressModeWithOperand::Accumulator) => 0x6a,
            (Mnemonic::JMP, AddressModeWithOperand::Indirect(_)) => 0x6c,
            (Mnemonic::ADC, AddressModeWithOperand::Absolute(_)) => 0x6d,
            (Mnemonic::ROR, AddressModeWithOperand::Absolute(_)) => 0x6e,
            (Mnemonic::BVS, AddressModeWithOperand::Relative(_)) => 0x70,
            (Mnemonic::ADC, AddressModeWithOperand::IndirectIndexed(_)) => 0x71,
            (Mnemonic::ADC, AddressModeWithOperand::ZeroPageIndexedWithX(_)) => 0x75,
            (Mnemonic::ROR, AddressModeWithOperand::ZeroPageIndexedWithX(_)) => 0x76,
            (Mnemonic::SEI, AddressModeWithOperand::Implied) => 0x78,
            (Mnemonic::ADC, AddressModeWithOperand::AbsoluteIndexedWithY(_)) => 0x79,
            (Mnemonic::ADC, AddressModeWithOperand::AbsoluteIndexedWithX(_)) => 0x7d,
            (Mnemonic::ROR, AddressModeWithOperand::AbsoluteIndexedWithX(_)) => 0x7e,
            (Mnemonic::STA, AddressModeWithOperand::IndexedIndirect(_)) => 0x81,
            (Mnemonic::STY, AddressModeWithOperand::ZeroPage(_)) => 0x84,
            (Mnemonic::STA, AddressModeWithOperand::ZeroPage(_)) => 0x85,
            (Mnemonic::STX, AddressModeWithOperand::ZeroPage(_)) => 0x86,
            (Mnemonic::DEY, AddressModeWithOperand::Implied) => 0x88,
            (Mnemonic::TXA, AddressModeWithOperand::Implied) => 0x8a,
            (Mnemonic::STY, AddressModeWithOperand::Absolute(_)) => 0x8c,
            (Mnemonic::STA, AddressModeWithOperand::Absolute(_)) => 0x8d,
            (Mnemonic::STX, AddressModeWithOperand::Absolute(_)) => 0x8e,
            (Mnemonic::BCC, AddressModeWithOperand::Relative(_)) => 0x90,
            (Mnemonic::STA, AddressModeWithOperand::IndirectIndexed(_)) => 0x91,
            (Mnemonic::STY, AddressModeWithOperand::ZeroPageIndexedWithX(_)) => 0x94,
            (Mnemonic::STA, AddressModeWithOperand::ZeroPageIndexedWithX(_)) => 0x95,
            (Mnemonic::STX, AddressModeWithOperand::ZeroPageIndexedWithY(_)) => 0x96,
            (Mnemonic::TYA, AddressModeWithOperand::Implied) => 0x98,
            (Mnemonic::STA, AddressModeWithOperand::AbsoluteIndexedWithY(_)) => 0x99,
            (Mnemonic::TXS, AddressModeWithOperand::Implied) => 0x9a,
            (Mnemonic::STA, AddressModeWithOperand::AbsoluteIndexedWithX(_)) => 0x9d,
            (Mnemonic::LDY, AddressModeWithOperand::Immediate(_)) => 0xa0,
            (Mnemonic::LDA, AddressModeWithOperand::IndexedIndirect(_)) => 0xa1,
            (Mnemonic::LDX, AddressModeWithOperand::Immediate(_)) => 0xa2,
            (Mnemonic::LDY, AddressModeWithOperand::ZeroPage(_)) => 0xa4,
            (Mnemonic::LDA, AddressModeWithOperand::ZeroPage(_)) => 0xa5,
            (Mnemonic::LDX, AddressModeWithOperand::ZeroPage(_)) => 0xa6,
            (Mnemonic::TAY, AddressModeWithOperand::Implied) => 0xa8,
            (Mnemonic::LDA, AddressModeWithOperand::Immediate(_)) => 0xa9,
            (Mnemonic::TAX, AddressModeWithOperand::Implied) => 0xaa,
            (Mnemonic::LDY, AddressModeWithOperand::Absolute(_)) => 0xac,
            (Mnemonic::LDA, AddressModeWithOperand::Absolute(_)) => 0xad,
            (Mnemonic::LDX, AddressModeWithOperand::Absolute(_)) => 0xae,
            (Mnemonic::BCS, AddressModeWithOperand::Relative(_)) => 0xb0,
            (Mnemonic::LDA, AddressModeWithOperand::IndirectIndexed(_)) => 0xb1,
            (Mnemonic::LDY, AddressModeWithOperand::ZeroPageIndexedWithX(_)) => 0xb4,
            (Mnemonic::LDA, AddressModeWithOperand::ZeroPageIndexedWithX(_)) => 0xb5,
            (Mnemonic::LDX, AddressModeWithOperand::ZeroPageIndexedWithY(_)) => 0xb6,
            (Mnemonic::CLV, AddressModeWithOperand::Implied) => 0xb8,
            (Mnemonic::LDA, AddressModeWithOperand::AbsoluteIndexedWithY(_)) => 0xb9,
            (Mnemonic::TSX, AddressModeWithOperand::Implied) => 0xba,
            (Mnemonic::LDY, AddressModeWithOperand::AbsoluteIndexedWithX(_)) => 0xbc,
            (Mnemonic::LDA, AddressModeWithOperand::AbsoluteIndexedWithX(_)) => 0xbd,
            (Mnemonic::LDX, AddressModeWithOperand::AbsoluteIndexedWithY(_)) => 0xbe,
            (Mnemonic::CPY, AddressModeWithOperand::Immediate(_)) => 0xc0,
            (Mnemonic::CMP, AddressModeWithOperand::IndexedIndirect(_)) => 0xc1,
            (Mnemonic::CPY, AddressModeWithOperand::ZeroPage(_)) => 0xc4,
            (Mnemonic::CMP, AddressModeWithOperand::ZeroPage(_)) => 0xc5,
            (Mnemonic::DEC, AddressModeWithOperand::ZeroPage(_)) => 0xc6,
            (Mnemonic::INY, AddressModeWithOperand::Implied) => 0xc8,
            (Mnemonic::CMP, AddressModeWithOperand::Immediate(_)) => 0xc9,
            (Mnemonic::DEX, AddressModeWithOperand::Implied) => 0xca,
            (Mnemonic::CPY, AddressModeWithOperand::Absolute(_)) => 0xcc,
            (Mnemonic::CMP, AddressModeWithOperand::Absolute(_)) => 0xcd,
            (Mnemonic::DEC, AddressModeWithOperand::Absolute(_)) => 0xce,
            (Mnemonic::BNE, AddressModeWithOperand::Relative(_)) => 0xd0,
            (Mnemonic::CMP, AddressModeWithOperand::IndirectIndexed(_)) => 0xd1,
            (Mnemonic::CMP, AddressModeWithOperand::ZeroPageIndexedWithX(_)) => 0xd5,
            (Mnemonic::DEC, AddressModeWithOperand::ZeroPageIndexedWithX(_)) => 0xd6,
            (Mnemonic::CLD, AddressModeWithOperand::Implied) => 0xd8,
            (Mnemonic::CMP, AddressModeWithOperand::AbsoluteIndexedWithY(_)) => 0xd9,
            (Mnemonic::CMP, AddressModeWithOperand::AbsoluteIndexedWithX(_)) => 0xdd,
            (Mnemonic::DEC, AddressModeWithOperand::AbsoluteIndexedWithX(_)) => 0xde,
            (Mnemonic::CPX, AddressModeWithOperand::Immediate(_)) => 0xe0,
            (Mnemonic::SBC, AddressModeWithOperand::IndexedIndirect(_)) => 0xe1,
            (Mnemonic::CPX, AddressModeWithOperand::ZeroPage(_)) => 0xe4,
            (Mnemonic::SBC, AddressModeWithOperand::ZeroPage(_)) => 0xe5,
            (Mnemonic::INC, AddressModeWithOperand::ZeroPage(_)) => 0xe6,
            (Mnemonic::INX, AddressModeWithOperand::Implied) => 0xe8,
            (Mnemonic::SBC, AddressModeWithOperand::Immediate(_)) => 0xe9,
            (Mnemonic::NOP, AddressModeWithOperand::Implied) => 0xea,
            (Mnemonic::CPX, AddressModeWithOperand::Absolute(_)) => 0xec,
            (Mnemonic::SBC, AddressModeWithOperand::Absolute(_)) => 0xed,
            (Mnemonic::INC, AddressModeWithOperand::Absolute(_)) => 0xee,
            (Mnemonic::BEQ, AddressModeWithOperand::Relative(_)) => 0xf0,
            (Mnemonic::SBC, AddressModeWithOperand::IndirectIndexed(_)) => 0xf1,
            (Mnemonic::SBC, AddressModeWithOperand::ZeroPageIndexedWithX(_)) => 0xf5,
            (Mnemonic::INC, AddressModeWithOperand::ZeroPageIndexedWithX(_)) => 0xf6,
            (Mnemonic::SED, AddressModeWithOperand::Implied) => 0xf8,
            (Mnemonic::SBC, AddressModeWithOperand::AbsoluteIndexedWithY(_)) => 0xf9,
            (Mnemonic::SBC, AddressModeWithOperand::AbsoluteIndexedWithX(_)) => 0xfd,
            (Mnemonic::INC, AddressModeWithOperand::AbsoluteIndexedWithX(_)) => 0xfe,
            _ => 0xea, // Defaults to NOP
        }
    }
}
